"""Analysis configuration dataclasses."""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Literal, Optional, Union

from bvidfe.core.geometry import PanelGeometry
from bvidfe.core.material import OrthotropicMaterial
from bvidfe.damage.state import DamageState
from bvidfe.impact.mapping import ImpactEvent


@dataclass
class MeshParams:
    """Mesh resolution parameters for the ``fe3d`` tier.

    All three knobs control how the hex8 mesh is generated by
    ``bvidfe.analysis.fe_mesh.build_fe_mesh``. Only ``in_plane_size_mm``
    and ``elements_per_ply`` directly affect the current mesh;
    ``cohesive_zone_factor`` is reserved for the cohesive-zone refinement
    pass (validated here, not yet consumed by the mesh builder).

    Parameters
    ----------
    elements_per_ply : int, default 1
        Number of through-thickness hex elements per physical ply. The
        z-direction node count is ``n_plies * elements_per_ply + 1``.
        Increase to resolve through-thickness gradients (e.g. interlaminar
        shear); doubling roughly doubles solve time. Must be a positive
        integer.
    in_plane_size_mm : float, default 5.0
        Target in-plane element edge length in millimetres. The builder
        uses ``nx = ceil(panel.Lx_mm / in_plane_size_mm)`` and the
        corresponding formula for y, so smaller values give a denser
        mesh (and quadratically more elements). Must be positive.
    cohesive_zone_factor : float, default 1.0
        Multiplier applied to the analytically estimated cohesive-zone
        characteristic length (Hillerborg) when sizing the local
        refinement target. ``1.0`` = exact estimate, ``<1`` coarser,
        ``>1`` finer. Reserved: the value is validated and round-tripped
        through ``config_io`` but is not yet consumed by the mesh builder.
        Must be positive.
    """

    elements_per_ply: int = 1
    in_plane_size_mm: float = 5.0
    cohesive_zone_factor: float = 1.0

    def __post_init__(self) -> None:
        if not isinstance(self.elements_per_ply, int) or self.elements_per_ply <= 0:
            raise ValueError(
                f"MeshParams.elements_per_ply must be a positive int "
                f"(got {self.elements_per_ply!r})"
            )
        if not (self.in_plane_size_mm > 0):
            raise ValueError(
                f"MeshParams.in_plane_size_mm must be > 0 " f"(got {self.in_plane_size_mm!r})"
            )
        if not (self.cohesive_zone_factor > 0):
            raise ValueError(
                f"MeshParams.cohesive_zone_factor must be > 0 "
                f"(got {self.cohesive_zone_factor!r})"
            )


@dataclass
class AnalysisConfig:
    """BVID analysis configuration. Provide exactly ONE of `impact` or `damage`."""

    material: Union[str, OrthotropicMaterial]
    layup_deg: List[float]
    ply_thickness_mm: float
    panel: PanelGeometry
    loading: Literal["compression", "tension"] = "compression"
    tier: Literal["empirical", "semi_analytical", "fe3d"] = "empirical"
    impact: Optional[ImpactEvent] = None
    damage: Optional[DamageState] = None
    mesh: Optional[MeshParams] = None

    def __post_init__(self) -> None:
        if (self.impact is None) == (self.damage is None):
            raise ValueError(
                "Provide exactly one of AnalysisConfig.impact or AnalysisConfig.damage"
            )
        if self.tier == "fe3d" and self.mesh is None:
            self.mesh = MeshParams()
